#!/usr/bin/env python3

import sys
import os
from ent import *

def main():
    if len(sys.argv) != 2:
        print('Supply one and only one executable to inspect')
        sys.exit()

    elf = ELF(sys.argv[1])
    print(elf)

if __name__ == '__main__':
    main()
